#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
ROOT="$(cd "$DIR/../../" && pwd)"

cd "$ROOT"
./.venv/bin/scons -j"$(nproc)" tools/imgui_cabana/_imgui_cabana

exec "$DIR/_imgui_cabana" "$@"
