import os

import imgui

Import('env', 'arch', 'common', 'messaging', 'visionipc', 'cereal', 'replay_lib')

imgui_env = env.Clone()
imgui_env['CPPPATH'] += [
  imgui.INCLUDE_DIR,
  '#tools/imgui_cabana/backends',
  '#third_party/json11',
]
imgui_env['CXXFLAGS'] += ['-Wno-unused-variable']

imgui_srcs = [
  os.path.join(imgui.SRC_DIR, src)
  for src in [
    'imgui.cpp',
    'imgui_draw.cpp',
    'imgui_tables.cpp',
    'imgui_widgets.cpp',
    'imgui_impl_opengl3.cpp',
  ]
]

imgui_srcs += ['backends/imgui_impl_glfw.cpp']

libs = ['/lib/x86_64-linux-gnu/libglfw.so']
frameworks = []
if arch == 'Darwin':
  frameworks += ['OpenGL', 'Cocoa', 'IOKit', 'CoreVideo']
else:
  libs += ['GL', 'dl', 'm', 'pthread']

imgui_env.Program(
  '_imgui_cabana',
  [
    'imgui_cabana.cc',
    'app_state.cc',
    'mainwin.cc',
    'messageswidget.cc',
    'binaryview.cc',
    'signalview.cc',
    'detailwidget.cc',
    'videowidget.cc',
    'chart/chartswidget.cc',
    'streams/replaystream.cc',
  ] + imgui_srcs,
  LIBS=[replay_lib, common, messaging, visionipc, cereal, 'json11', 'avformat', 'avcodec', 'swresample', 'avutil', 'x264', 'z', 'bz2', 'zstd', 'yuv', 'ncurses'] + libs,
  FRAMEWORKS=frameworks,
)
