import os

import imgui
import libusb_package
import nanosvg

Import('env', 'arch', 'common', 'messaging', 'visionipc', 'cereal', 'replay_lib')

# ---- Cabana build ----
cabana_env = env.Clone()

# libusb: headers from system, shared lib from pip package
libusb_lib_path = str(libusb_package.get_library_path())
libusb_lib_dir = os.path.dirname(libusb_lib_path)
cabana_env['LIBPATH'] += [libusb_lib_dir]

cabana_env['CPPPATH'] += [imgui.INCLUDE_DIR, nanosvg.INCLUDE_DIR, '#tools/cabana/include']
opendbc_path = '-DOPENDBC_FILE_PATH=\'"%s"\'' % (cabana_env.Dir("../../opendbc/dbc").abspath)
cabana_env['CXXFLAGS'] += [opendbc_path, '-DGLFW_INCLUDE_NONE']

cabana_srcs = [
  'imgui/settings.cc', 'imgui/commands.cc',
  'imgui/stream.cc', 'imgui/livestream.cc',
  'imgui/replaystream.cc', 'imgui/devicestream.cc',
  'imgui/pandastream.cc',
  'imgui/dbcmanager.cc', 'imgui/dbcfile.cc',
  'imgui/util.cc', 'imgui/export.cc',
  'imgui/bootstrap.cc',
]
if arch != "Darwin":
  cabana_srcs += ['imgui/socketcanstream.cc']

# Shared sources built with unique object names so Cabana outputs do not collide with other workspace targets.
cabana_shared_srcs = {
  'cabana_dbc': 'dbc/dbc.cc',
  'cabana_message_list': 'core/message_list.cc',
  'cabana_persistent_state': 'core/persistent_state.cc',
  'cabana_workspace_state': 'core/workspace_state.cc',
  'cabana_launch_config': 'core/launch_config.cc',
  'cabana_panda': 'panda.cc',
}
cabana_shared_objs = [cabana_env.Object(target=name, source=src) for name, src in cabana_shared_srcs.items()]

cabana_base_libs = [common, messaging, cereal, visionipc, replay_lib,
                    'avformat', 'avcodec', 'swresample', 'avutil',
                    'x264', 'z', 'bz2', 'zstd', 'yuv', 'usb-1.0',
                    'capnp', 'kj',
                    'm', 'ssl', 'crypto', 'pthread']
if arch != "Darwin":
  cabana_base_libs += ['va', 'va-drm', 'drm']

cabana_backend_lib = cabana_env.Library("cabana_backend_lib", cabana_srcs + cabana_shared_objs, LIBS=cabana_base_libs)

cabana_app_env = cabana_env.Clone()
cabana_app_env['LIBPATH'] += [imgui.LIB_DIR]
# Link against pre-built imgui and glfw3 from the imgui package
cabana_libs = ['imgui', 'glfw3', 'json11', 'jpeg'] + cabana_base_libs
if arch == "Darwin":
  cabana_frameworks = ['Cocoa', 'IOKit', 'CoreVideo', 'OpenGL']
else:
  cabana_frameworks = []
  cabana_libs += ['dl', 'rt']
  cabana_app_env['LINKFLAGS'] += ['-Wl,--strip-debug']
  cabana_app_env['LINKCOM'] = cabana_app_env['LINKCOM'].replace(
    '$_LIBFLAGS', '-Wl,--start-group $_LIBFLAGS -Wl,--end-group')

cabana_main = cabana_app_env.Object('cabana_main', 'imgui/main.cc')
cabana_app = cabana_app_env.Object('cabana_app', 'imgui/app.cc')
cabana_app_util = cabana_app_env.Object('cabana_app_util', 'imgui/app_util.cc')
cabana_app_panels = cabana_app_env.Object('cabana_app_panels', 'imgui/app_panels.cc')
cabana_app_detail_panels = cabana_app_env.Object('cabana_app_detail_panels', 'imgui/app_detail_panels.cc')
cabana_app_dialogs = cabana_app_env.Object('cabana_app_dialogs', 'imgui/app_dialogs.cc')
cabana_icons = cabana_app_env.Object('cabana_icons', 'imgui/icons.cc')
cabana_app_env.Program('cabana', [cabana_main, cabana_app, cabana_app_util, cabana_app_panels, cabana_app_detail_panels, cabana_app_dialogs, cabana_icons, cabana_backend_lib],
                       LIBS=cabana_libs, FRAMEWORKS=cabana_frameworks)
