#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
ROOT="$(cd "$DIR/../../" && pwd)"

cd "$ROOT"
scons -j4 tools/cabana_imgui/_cabana_imgui

exec "$DIR/_cabana_imgui" "$@"
