#!/usr/bin/env python3
"""Generate bootstrap_icons_font_data.h from the Bootstrap Icons WOFF font.

Run from repo root:
  python3 tools/jotpluggler/generate_bootstrap_icons_font.py

Requires fonttools: pip install fonttools
"""

from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
WOFF_PATH = ROOT / "third_party" / "bootstrap" / "icons" / "font" / "fonts" / "bootstrap-icons.woff"
OUTPUT_PATH = ROOT / "tools" / "jotpluggler" / "bootstrap_icons_font_data.h"


def main():
  if not WOFF_PATH.exists():
    print(f"WOFF not found at {WOFF_PATH}")
    print("Run: cd third_party/bootstrap && bash pull.sh")
    raise SystemExit(1)

  font = TTFont(str(WOFF_PATH))
  font.flavor = None  # WOFF → raw TTF

  import io
  buf = io.BytesIO()
  font.save(buf)
  data = buf.getvalue()

  assert data[:4] == b'\x00\x01\x00\x00', f"Bad TTF magic: {data[:4].hex()}"

  lines = [
    "// Bootstrap Icons TTF font",
    "// https://github.com/twbs/icons",
    "// MIT License",
    f"// Generated by {Path(__file__).relative_to(ROOT)}",
    "",
    "#pragma once",
    "",
    "#include <cstddef>",
    "",
    f"static const unsigned int kBootstrapIconsFontSize = {len(data)};",
    f"static const unsigned char kBootstrapIconsFontData[{len(data)}] = {{",
  ]

  for i in range(0, len(data), 20):
    chunk = data[i:i + 20]
    lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

  lines.append("};")
  lines.append("")

  OUTPUT_PATH.write_text("\n".join(lines))
  print(f"{WOFF_PATH.name} ({len(data)} bytes TTF) -> {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
  main()
