#!/usr/bin/env python3

from __future__ import annotations

import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SPRITE_PATH = ROOT / "third_party" / "bootstrap" / "bootstrap-icons.svg"
OUTPUT_PATH = ROOT / "tools" / "jotpluggler" / "bootstrap_icons_generated.inc"
ICON_SIZE = 20
ICON_IDS = [
  "sliders",
  "palette",
  "plus-slash-minus",
  "distribute-horizontal",
  "distribute-vertical",
  "zoom-out",
  "arrow-left-right",
  "arrow-down-up",
  "trash",
  "files",
  "clipboard2",
  "file-earmark-image",
  "save",
  "bar-chart",
  "x-square",
]


def extract_symbol(sprite: str, icon_id: str) -> str:
  pattern = re.compile(rf'<symbol([^>]*)id="{re.escape(icon_id)}"([^>]*)>(.*?)</symbol>', re.DOTALL)
  match = pattern.search(sprite)
  if match is None:
    raise RuntimeError(f"missing bootstrap icon '{icon_id}'")
  attrs = (match.group(1) + match.group(2)).strip()
  body = match.group(3)
  return f'<svg xmlns="http://www.w3.org/2000/svg" {attrs}>{body}</svg>'


def rasterize_alpha(svg_text: str) -> list[int]:
  command = [
    "convert",
    "svg:-",
    "-background",
    "white",
    "-alpha",
    "remove",
    "-alpha",
    "off",
    "-colorspace",
    "Gray",
    "-resize",
    f"{ICON_SIZE}x{ICON_SIZE}!",
    "txt:-",
  ]
  result = subprocess.run(command, input=svg_text, text=True, check=True, capture_output=True)
  values = [255] * (ICON_SIZE * ICON_SIZE)
  lines = result.stdout.splitlines()
  if not lines:
    raise RuntimeError("convert produced no output")
  header = re.match(r"# ImageMagick pixel enumeration: \d+,\d+,(\d+),", lines[0])
  if header is None:
    raise RuntimeError("unexpected convert output header")
  max_value = int(header.group(1))
  for line in lines[1:]:
    match = re.match(r"(\d+),(\d+):\s+\((\d+),", line)
    if match is None:
      continue
    x = int(match.group(1))
    y = int(match.group(2))
    gray = round(int(match.group(3)) * 255 / max_value)
    values[y * ICON_SIZE + x] = max(0, min(255, 255 - gray))
  return values


def format_bytes(values: list[int]) -> str:
  lines: list[str] = []
  for i in range(0, len(values), 20):
    chunk = ", ".join(f"{value:3d}" for value in values[i:i + 20])
    lines.append(f"  {chunk},")
  return "\n".join(lines)


def main() -> None:
  sprite = SPRITE_PATH.read_text()
  pieces = [
    "// Generated by tools/jotpluggler/generate_bootstrap_icon_header.py",
    "// Do not edit by hand.",
    "",
  ]
  table_rows: list[str] = []
  for icon_id in ICON_IDS:
    symbol = extract_symbol(sprite, icon_id)
    alpha = rasterize_alpha(symbol)
    symbol_name = icon_id.replace("-", "_")
    pieces.append(f"static constexpr unsigned char kBootstrapIcon_{symbol_name}[] = {{")
    pieces.append(format_bytes(alpha))
    pieces.append("};")
    pieces.append("")
    table_rows.append(f'  {{ "{icon_id}", {ICON_SIZE}, {ICON_SIZE}, kBootstrapIcon_{symbol_name} }},')

  pieces.append("static constexpr RasterizedBootstrapIconData kBootstrapIcons[] = {")
  pieces.extend(table_rows)
  pieces.append("};")
  pieces.append("")
  OUTPUT_PATH.write_text("\n".join(pieces))


if __name__ == "__main__":
  main()
