import os

import imgui

Import('env', 'arch', 'common', 'messaging', 'visionipc', 'cereal')
Import('replay_lib')

jot_env = env.Clone()
jot_env["LIBPATH"] += [imgui.MESA_DIR]
jot_env["CPPPATH"] += [imgui.INCLUDE_DIR]
jot_env["CXXFLAGS"] += ["-DGLFW_INCLUDE_NONE"]

jot_sources = [
  "main.cc",
  "app.cc",
  "bootstrap_icons.cc",
  "sketch_layout.cc",
]

objects = []
for source in jot_sources:
  basename = os.path.splitext(os.path.basename(source))[0]
  objects.append(jot_env.Object(target=f"jot_{basename}", source=source))

imgui_static = File(f"{imgui.LIB_DIR}/libimgui.a")
glfw_static = File(f"{imgui.LIB_DIR}/libglfw3.a")
frameworks = []
libs = [replay_lib, common, messaging, visionipc, cereal, imgui_static, glfw_static,
        "avformat", "avcodec", "swresample", "avutil", "x264", "yuv", "z", "bz2", "zstd", "m", "pthread"]
if arch == "Darwin":
  frameworks = ["OpenGL", "Cocoa", "IOKit", "CoreFoundation", "CoreVideo"]
else:
  libs += ["GL", "dl"]

jot_env.Program("jotpluggler", objects, LIBS=libs, FRAMEWORKS=frameworks)
